name: money_tracker
description: A money tracking app with multiple profiles.
publish_to: 'none'

version: 1.3.0+5

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  intl: ^0.19.0
  fl_chart: ^0.66.2
  share_plus: ^7.2.2
  url_launcher: ^6.1.14
  shared_preferences: ^2.5.3
  android_intent_plus: ^4.0.3
  device_info_plus: ^9.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
