name: money_tracker
description: A money tracking app with multiple profiles.
publish_to: 'none'

version: 2.0.0+10

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  intl: ^0.20.2
  fl_chart: ^0.66.2
  share_plus: ^7.2.2
  url_launcher: ^6.1.14
  shared_preferences: ^2.5.3
  android_intent_plus: ^4.0.3
  device_info_plus: ^9.1.2
  package_info_plus: ^8.3.0
  google_mobile_ads: ^5.0.0  # Use the latest version
  firebase_core: ^2.15.0
  firebase_analytics: ^10.0.0
  firebase_messaging: ^14.0.0 # Use the latest version
  firebase_dynamic_links: ^5.4.14 # Use Dynamic Links instead of App Indexing
  flutter_local_notifications: ^14.0.0 # Use the latest version
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true